#!/bin/sh

src="$1"
dest="$2"

[ -z "$src" ] && src="../src"
[ -z "$dest" ] && dest="../www"

[ $(basename $0) = "clean" ] && rm -rf $(find $dest | grep -vE "^$dest(/res)?$") && exit

build_dir () {
	[ -z "$1" ] && return
	[ -d "$1" ] || mkdir "$1"
}

build_item () {
	[ -z "$1" ] && return # filename
	[ -z "$2" ] && return # template
	replacer/replace "$1" -t "$2" -c ./smu -T "$(title $1)" -D "$(date '+%a, %d %b %Y %R:%S %z')"
}

title () {
	grep -E "^[#][^#]" "$1" | head -n 1 | sed 's/ //' | cut -f2 -d'#'
}

for i in $(find $src | grep -vE "\.ssgignore|template*|res/"); do
	target=$(echo "$i" | sed "s $src $dest " | sed "s/.md$/.html/")
	# Decide whether to build or not
	build_i=''
	[ -d "$i" ] && build_dir "$target" && continue
	[ -f "$target" ] || build_i=yes
	[ -z $build_i ] && [ $(stat -c %Y "$i") -gt $(stat -c %Y "$target") ] && build_i=yes
	[ -z $build_i ] && continue
	# Build
	echo "Building $target from $i"
	replacer/replace "$i" -t "$src/template.html" -c ./smu -T "$(title $i)" > "$target"
done

# TODO create blog
mkdir "$dest/.tmp"
[ -f "$dest/rss.xml" ] && rm "$dest/rss.xml"
for i in $(find "$src/blog" | grep -v "^$src/blog$"); do
	echo -e "$(stat -c %W $i)\t$i"
done | sort -n | tail -n 10 | cut -f2 | for i in $(cat); do
	echo $i
	build_item $i "$src/template_rss.xml" >> "$dest/.tmp/rss.xml"
done
replacer/replace "$dest/.tmp/rss.xml" -t "$src/template_rssi.xml" -c /usr/bin/cat >> "$dest/rss.xml"
rm -rf "$dest/.tmp"
