#!/bin/sh

src="$1"
dest="$2"

build_dir () {
	[ -z "$1" ] && return
	[ -d "$1" ] || mkdir "$1"
}

build_item () {
	[ -z "$1" ] && return # filename
	[ -z "$2" ] && return # template
	[ -z "$3" ] && return # date format
	time="$(stat -c %w $1)"
	replacer/replace "$1" -t "$2" -c ./smu -T "$(title $1)" -D "$(date "$3" -d "$time")" -U "$(target $1 "$websitename")"
}

build_items () {
	[ -z "$1" ] && return # item
	echo "$1"
	build_item "$1" "$src/template_rss.xml" -R >> "$dest/.tmp/rss.xml"
}

title () {
	grep -E "^[#][^#]" "$1" | head -n 1 | sed 's/ //' | cut -f2 -d'#'
}

target () {
	[ -z "$1" ] && return # filename
	[ -z "$2" ] && return # prefix
	echo "$1" | sed "s $src $2 " | sed "s/.md$/.html/"
}

build_blog () {
	[ -z "$1" ] && return # blogdir
	[ -d "$dest/$1" ] || return # blogdir does not exit
	[ -z "$2" ] && return # blogtitle
	mkdir "$dest/.tmp"
	[ -f "$dest/rss.xml" ] && rm "$dest/rss.xml"
	for i in $(find "$src/$1" | grep -v "^$src/$1$"); do
		echo -e "$(stat -c %W $i)\t$i"
	done | sort -rn | head -n 10 | cut -f2 | for i in $(cat); do
		build_items "$i"
	done
	build_feed "$1" "$2"
	rm -rf "$dest/.tmp"
}

build_feed () {
	[ -z "$1" ] && return # blogdir
	[ -z "$2" ] && return # blogtitle
	replacer/replace "$dest/.tmp/rss.xml" -t "$src/template_rssi.xml" -c /usr/bin/cat > "$dest/$1/rss.xml"
}

[ -f ./config.sh ] && . ./config.sh
[ $(basename $0) = "clean" ] && echo $(find $dest | grep -vE "^$dest(/res)?$") && exit


for i in $(find $src | grep -vE "\.ssgignore|template*|res/"); do
	target=$(target "$i" "$dest")
	# Decide whether to build or not
	build_i=''
	[ -d "$i" ] && build_dir "$target" && continue
	[ -f "$target" ] || build_i=yes
	[ -z $build_i ] && [ $(stat -c %Y "$i") -gt $(stat -c %Y "$target") ] && build_i=yes
	[ -z $build_i ] && continue
	# Build
	echo "Building $target from $i"
	replacer/replace "$i" -t "$src/template.html" -c ./smu -T "$(title $i)" > "$target"
done

# TODO create blog
[ -z "$blogdirs" ] || for i in ${!blogdirs[@]}; do
	echo "Building ${blogdirs[i]} with title ${blogtitles[i]}"
	build_blog "${blogdirs[i]}" "${blogtitles[i]}"
done
